name: Release

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        yarn install --frozen-lockfile
        yarn lint
    - uses: cycjimmy/semantic-release-action@v2
      env:
        # NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
